SELECT P.DESCRICAO,
	P.UNIDADE,
	IP.QUANTIDADE
FROM PRODUTO P
LEFT JOIN ITEM_PEDIDO IP ON P.CODIGO_PRODUTO = IP.CODIGO_PRODUTO;


SELECT P.DESCRICAO,
	P.UNIDADE,
	IP.QUANTIDADE
FROM PRODUTO P
LEFT JOIN ITEM_PEDIDO IP ON P.CODIGO_PRODUTO = IP.CODIGO_PRODUTO
WHERE IP.QUANTIDADE IS NULL;

-- RIGHT

SELECT P.DESCRICAO,
	P.UNIDADE,
	IP.QUANTIDADE
FROM ITEM_PEDIDO IP
RIGHT OUTER JOIN PRODUTO P ON P.CODIGO_PRODUTO = IP.CODIGO_PRODUTO;


SELECT C.NOME_CLIENTE,
	P.PRAZO_ENTREGA
FROM PEDIDO P
RIGHT OUTER JOIN CLIENTE C ON P.CODIGO_CLIENTE = C.CODIGO_CLIENTE;


SELECT V.NOME_VENDEDOR,
	P.PRAZO_ENTREGA
FROM PEDIDO P
RIGHT OUTER JOIN VENDEDOR V ON P.CODIGO_VENDEDOR = V.CODIGO_VENDEDOR;

INSERT INTO vendedor VALUES(350, 'Rafael Callegari', 3333, 'B'); 

-- ex1 sala
SELECT v.nome_vendedor, c.nome_cliente, p.prazo_entrega
	FROM pedido p RIGHT OUTER JOIN vendedor v
	ON p.codigo_vendedor = v.codigo_vendedor
	RIGHT OUTER JOIN cliente c
 	ON c.codigo_cliente = p.codigo_cliente;
